repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff lint
        entry: backend/scripts/run_poetry.sh -C backend run ruff check --fix
        language: system
        pass_filenames: false
      - id: ruff-format
        name: ruff format
        entry: backend/scripts/run_poetry.sh -C backend run ruff format
        language: system
        pass_filenames: false
