export const metadata = {
  title: "Política de Privacidad · Geoactiv",
  description: "Conoce cómo Geoactiv procesa tus datos al usar la plataforma TalIA.",
};

const definitionItems = [
  ["Account", "a unique account created for You to access our Service or parts of our Service."],
  [
    "Affiliate",
    'an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.',
  ],
  ["Application", "Talia App Mesanger, the software program provided by the Company."],
  ["Company", 'Geoactiv s.a. de c.v., De La Leona 8, Mellado, 36010 Guanajuato, Gto.'],
  [
    "Cookies",
    "small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.",
  ],
  ["Country", "Mexico"],
  [
    "Device",
    "any device that can access the Service such as a computer, a cell phone or a digital tablet.",
  ],
  ["Personal Data", "any information that relates to an identified or identifiable individual."],
  ["Service", "the Application or the Website or both."],
  [
    "Service Provider",
    "any natural or legal person who processes the data on behalf of the Company.",
  ],
  [
    "Usage Data",
    "data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.",
  ],
  ["Website", "Geoactiv, accessible from https://geoactiv.mx/"],
  [
    "You",
    "the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service.",
  ],
];

const dataTypes = [
  "Email address",
  "First name and last name",
  "Phone number",
  "Address, State, Province, ZIP/Postal code, City",
];

const trackingTechnologies = [
  [
    "Cookies or Browser Cookies",
    "A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service.",
  ],
  [
    "Web Beacons",
    "Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company to count users who have visited those pages or opened an email.",
  ],
];

const cookiePurposes = [
  {
    title: "Necessary / Essential Cookies",
    type: "Session Cookies",
    administeredBy: "Us",
    purpose:
      "These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features.",
  },
  {
    title: "Cookies Policy / Notice Acceptance Cookies",
    type: "Persistent Cookies",
    administeredBy: "Us",
    purpose: "These Cookies identify if users have accepted the use of cookies on the Website.",
  },
  {
    title: "Functionality Cookies",
    type: "Persistent Cookies",
    administeredBy: "Us",
    purpose:
      "These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.",
  },
];

const usagePurposes = [
  "To provide and maintain our Service, including to monitor the usage of our Service.",
  "To manage Your Account: to manage Your registration as a user of the Service.",
  "For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased.",
  "To contact You: by email, telephone calls, SMS, or other equivalent forms of electronic communication, such as push notifications.",
  "To provide You with news, special offers, and general information about other goods, services and events which We offer that are similar to those that you have already purchased or inquired about.",
  "To manage Your requests: to attend and manage Your requests to Us.",
  "For business transfers: We may use Your information to evaluate or conduct a merger, divestiture or other sale or transfer of assets.",
  "For other purposes: data analysis, identifying usage trends, determining effectiveness of campaigns and improving our Service.",
];

const sharingScenarios = [
  "With Service Providers: to monitor and analyze the use of our Service, to contact You.",
  "For business transfers: in connection with mergers, sales of assets or financing.",
  "With Affiliates: our parent company and any subsidiaries or joint ventures.",
  "With business partners: to offer You certain products, services or promotions.",
  "With other users: when You share personal information in public areas.",
  "With Your consent: for any other purpose with Your consent.",
];

export default function PrivacyPolicyPage() {
  return (
    <main className="mx-auto max-w-4xl px-6 py-16 text-foreground">
      <article className="space-y-8">
        <header className="space-y-2">
          <p className="text-sm uppercase tracking-[0.25em] text-muted-foreground">
            Privacy Policy for Geoactiv
          </p>
          <h1 className="text-4xl font-semibold leading-tight">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">Last updated: December 26, 2025</p>
        </header>

        <section className="space-y-3">
          <p>
            This Privacy Policy describes Our policies and procedures on the collection, use and
            disclosure of Your information when You use the Service and tells You about Your privacy
            rights and how the law protects You.
          </p>
          <p>
            We use Your Personal data to provide and improve the Service. By using the Service, You
            agree to the collection and use of information in accordance with this Privacy Policy.
          </p>
          <p>This Privacy Policy has been created with the help of the Privacy Policy Generator.</p>
        </section>

        <section>
          <h2 className="text-2xl font-semibold">Interpretation and Definitions</h2>
          <p className="text-sm text-muted-foreground">
            Interpretation: the words whose initial letters are capitalized have meanings defined
            under the following conditions. They have the same meaning whether they appear in
            singular or plural.
          </p>
          <h3 className="mt-4 text-xl font-semibold">Definitions</h3>
          <div className="mt-4 space-y-4 rounded-lg border p-4 bg-background">
            {definitionItems.map(([term, description]) => (
              <div key={term}>
                <strong className="text-sm uppercase tracking-wider text-muted-foreground">
                  {term}
                </strong>
                <p className="mt-1 text-sm leading-relaxed text-foreground">{description}</p>
              </div>
            ))}
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">Collecting and Using Your Personal Data</h2>
          <p className="text-lg font-semibold">Types of Data Collected</p>

          <div className="rounded-lg border p-4 bg-background">
            <h3 className="text-lg font-semibold">Personal Data</h3>
            <ul className="mt-2 list-disc space-y-1 pl-5 text-sm">
              {dataTypes.map((type) => (
                <li key={type}>{type}</li>
              ))}
              <li>Usage Data</li>
            </ul>
            <p className="mt-3 text-sm text-muted-foreground">
              Usage Data is collected automatically when using the Service and may include information
              such as Your Device&apos;s IP address, browser type, the pages You visit and other
              diagnostic data.
            </p>
            <p className="text-sm text-muted-foreground">
              When You access the Service from a mobile device, We may collect Your device model,
              unique ID, IP address, operating system, browser type, and other diagnostic data.
            </p>
            <p className="text-sm text-muted-foreground">
              We may also collect information that Your browser sends whenever You visit Our Service
              or when You access it through a mobile device.
            </p>
          </div>

          <div className="rounded-lg border p-4 bg-background">
            <h3 className="text-lg font-semibold">Information Collected while Using the Application</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              While using Our Application, and with Your prior permission, We may collect location
              data, access to Your device&apos;s contacts, camera, and photo library.
            </p>
            <p className="text-sm text-muted-foreground">
              We use this information to power the Service and may upload it to the Company&apos;s or
              a Service Provider&apos;s servers or store it locally on Your device. You can enable or
              disable access through Your Device settings.
            </p>
          </div>

          <div className="rounded-lg border p-4 bg-background">
            <h3 className="text-lg font-semibold">Tracking Technologies and Cookies</h3>
            <p className="mt-2 text-sm text-muted-foreground">
              We use Cookies and similar technologies to track activity and store certain
              information. These include beacons, tags, and scripts to collect data and improve the
              Service.
            </p>
            <div className="mt-3 space-y-3">
              {trackingTechnologies.map(([name, description]) => (
                <div key={name}>
                  <strong className="block text-sm uppercase tracking-wider text-muted-foreground">
                    {name}
                  </strong>
                  <p className="text-sm text-foreground">{description}</p>
                </div>
              ))}
            </div>
            <p className="mt-3 text-sm text-muted-foreground">
              Cookies can be &quot;Persistent&quot; or &quot;Session&quot; cookies. We use both to enable
              features and personalize the experience.
            </p>
            <div className="mt-3 space-y-3">
              {cookiePurposes.map((cookie) => (
                <div key={cookie.title} className="rounded border p-3">
                  <p className="text-sm font-semibold">{cookie.title}</p>
                  <p className="text-xs uppercase text-muted-foreground">
                    Type: {cookie.type} · Administered by: {cookie.administeredBy}
                  </p>
                  <p className="text-sm">{cookie.purpose}</p>
                </div>
              ))}
            </div>
            <p className="mt-3 text-sm text-muted-foreground">
              For more details visit our Cookies Policy or the Cookies section of the Privacy Policy.
            </p>
          </div>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">Use of Your Personal Data</h2>
          <ul className="list-disc space-y-2 pl-5 text-sm text-foreground">
            {usagePurposes.map((purpose) => (
              <li key={purpose}>{purpose}</li>
            ))}
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">Sharing Your Personal Data</h2>
          <ul className="list-disc space-y-2 pl-5 text-sm text-foreground">
            {sharingScenarios.map((scenario) => (
              <li key={scenario}>{scenario}</li>
            ))}
          </ul>
          <p className="mt-2 text-sm text-muted-foreground">
            The Company retains Your Personal Data only while it is necessary and may keep Usage Data
            for internal analysis.
          </p>
          <p className="text-sm text-muted-foreground">
            Transfers outside Your jurisdiction follow appropriate safeguards.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-2xl font-semibold">Additional Rights and Notices</h2>
          <p className="text-sm text-muted-foreground">
            You may delete or update Your information at any time via the Service or by contacting us.
            We may retain data to satisfy legal obligations or when retaining is necessary for security.
          </p>
          <p className="text-sm text-muted-foreground">
            We may disclose Personal Data for business transactions, law enforcement cooperation, or
            other legal requirements in good faith to protect rights, safety, or property.
          </p>
          <p className="text-sm text-muted-foreground">
            Security is important to Us, but no method of transmission or storage is 100% secure.
          </p>
          <p className="text-sm text-muted-foreground">
            The Service does not address anyone under the age of 13. If we become aware of data
            collected from a child without parental consent, we will remove it.
          </p>
          <p className="text-sm text-muted-foreground">
            Links to other websites are outside our control. Review their privacy practices before
            sharing data.
          </p>
          <p className="text-sm text-muted-foreground">
            We may update this Privacy Policy and will post changes on this page with the new
            effective date.
          </p>
          <p className="text-sm text-muted-foreground">
            Questions? Contact us via email at{" "}
            <a className="text-primary underline" href="mailto:administracion@talia.mx">
              administracion@talia.mx
            </a>
            .
          </p>
        </section>
      </article>
    </main>
  );
}
